### ISSUE TITLE
pandoc-zotxt: TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by pymander** [egh/zotxt#4]
Trying to run pandoc like this:

    pandoc -F pandoc-zotxt -F pandoc-citeproc -f org -t markdown_github -o test.md AstrologyHouseMnemonic.org

Results in this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-zotxt", line 9, in <module>
    load_entry_point('pandoc-zotxt==5.0.2', 'console_scripts', 'pandoc-zotxt')()
  File "build/bdist.linux-x86_64/egg/pandoczotxt/__init__.py", line 90, in run
  File "build/bdist.linux-x86_64/egg/pandoczotxt/__init__.py", line 38, in toJSONFilter
TypeError: list indices must be integers, not str
pandoc: Error running filter pandoc-zotxt
Filter returned error status 1
```

I am using python 2.7 on Ubuntu 17.04.

**Comment by egh** [comment]
I'm not working on the `pandoc-zotxt` python plugin. I suggest you use https://github.com/odkr/pandoc-zotxt.lua Thanks for the report!
