### ISSUE TITLE
Python error: File not found.

### ISSUE THREAD

**Issue by HaoZeke** [egh/zotxt#6]
# Bug Report

## Details

```bash
Collecting pandoc-zotxt
  Downloading https://files.pythonhosted.org/packages/27/70/00eb7db38200f8ad08e18ac65056d320dc8eeab744c0760cbfbe5bc1d1f1/pandoc-zotxt-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-caky9ev4/pandoc-zotxt/setup.py", line 10, in <module>
        with open(path.join(here, '..', 'README.rst'), encoding='utf-8') as f:
      File "/home/haozeke/.virtualenvs/bTechProjFin-O5xos1BV/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-caky9ev4/pandoc-zotxt/../README.rst'
    
    ----------------------------------------

Error:  An error occurred while installing pandoc-zotxt!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-caky9ev4/pandoc-zotxt/
``` 

This seems related to #3 but it differs in the file missing.

**Comment by egh** [comment]
Thanks for the report! I'm not working on pandoc-zotxt (python) any more. I suggest you look at https://github.com/odkr/pandoc-zotxt.lua
